# Basic
title: 只为此心无垠  #博客名
subtitle: A blog for Jekyll #博客副标题
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 凤凰花开开两季，之余青春止于青春  #博客描述
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
   # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    - {title: 关于, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: zx
    github: zx
    twitter: zx
    gplus: 107108267983477358170
    mail: 1724366293@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
